docker/mock-nhsid-jwks/src/jwks/IdTokenNHSIDIdentityServiceTestsJWKS.json

AMB-520 add test key to key store

---

azure/azure-pr-pipeline.yml
azure/azure-release-pipeline.yml

pipeline fix

---

docker/mock-nhsid-jwks/src/jwks/IdTokenNHSIDIdentityServiceTestsJWKS.json

AMB-520 rotate key

---

docker/mock-nhsid-jwks/src/jwks/IdTokenNHSIDIdentityServiceTestsJWKS.json

AMB-520 rotate to test 3 key

---

docker/mock-nhsid-jwks/src/mockEndpoints/IdTokenNHSIDIdentityServiceTestsJWKS.json

AMB-520 rotate to test-2 key

---

api_tests/user_role_shared_flow/test_cases.py

AMB-563 chage error codes and descriptions

---

api_tests/user_role_shared_flow/test_cases.py

AMB-563 fix typo in error message

---

docker/mock-nhsid-jwks/src/mockEndpoints/IdTokenNHSIDIdentityServiceTestsJWKS.json

AMB-520 rotate keys to test-3

---

docker/mock-nhsid-jwks/src/mockEndpoints/IdTokenNHSLoginServiceTestsJWKS.json
docker/mock-nhsid-jwks/src/routes/routes.js

AMB-601 add new mock jwks endpoint

---

docker/mock-nhsid-jwks/src/mockEndpoints/IdTokenNHSCIS2IdentityServiceTestsJWKS.json
docker/mock-nhsid-jwks/src/routes/routes.js

AMB-601 Add new endpoint for nhs cis2 keys

---

docker/mock-nhsid-jwks/src/mockEndpoints/IdTokenNHSLoginServiceTestsJWKS.json

New 512 pub key for mock nhs login

AMB-605 Add new 512 key for nhs login mock

---

azure/azure-release-pipeline.yml

apm-2203: deploy mock ids to ref

---

Makefile

apm-2203: deploy hosted target to ref too

---

azure/azure-pr-pipeline.yml
proxies/live/apiproxy/policies/AssignMessage.SimulatedTokenPayload.xml
proxies/live/apiproxy/proxies/default.xml

AMB-724 Add long term id_token

---

Makefile
api_tests/config_files/config.py
api_tests/user_role_shared_flow/test_cases.py
azure/azure-pr-pipeline.yml
azure/azure-release-pipeline.yml
proxies/live/apiproxy/proxies/default.xml

Add tests to check mock responses and status codes

AMB-735 Add tests for simulated token response

---

Makefile
azure/azure-release-pipeline.yml

AMB-735 Add int to release pipeline

---

azure/azure-release-pipeline.yml

AMB-737 Add KVM to release pipeline

---

azure/azure-release-pipeline.yml

AMB-737 use identity_service_config_no_smarcard kvm on INT

---

api_tests/README.md
api_tests/user_role_shared_flow/test_cases.py
proxies/live/apiproxy/policies/AssignMessage.GenerateUserinfoResponseSimulatedAuth.xml
proxies/live/apiproxy/proxies/default.xml

AMB-736 Corrected error in test documentation

---

azure/azure-release-pipeline.yml

AMB-722 use mock_proxy_config in int environment

---

proxies/live/apiproxy/policies/AssignMessage.SimulatedAuthPageNHSLogin.xml

AMB-722 update NHS Login landing page

---

proxies/live/apiproxy/policies/AssignMessage.RedirectToApigeeCallbackCIS2.xml
proxies/live/apiproxy/policies/AssignMessage.RedirectToApigeeCallbackNHSLogin.xml
proxies/live/apiproxy/proxies/default.xml

AMB-000 roll back latest changes

---

api_tests/auth/test_cases.py
api_tests/config_files/config.py
api_tests/config_files/environments.py
api_tests/conftest.py
api_tests/requirements.txt
api_tests/user_role_shared_flow/test_cases.py
azure/templates/run-integration-tests.yml

Add test coverage for authentication methods

AMB-789 Add test coverage for authentication methods

---

azure/azure-release-pipeline.yml

AMB-789 activate integration tests on release

---

azure/templates/run-integration-tests.yml

AMB-789 use service base path on test variablez

---

docker/mock-nhsid-jwks/src/mockEndpoints/IdTokenNHSLoginServiceTestsJWKS.json

AMB-1243 adding a second entry to have the same kid as we have on key

---

.gitignore
api_tests/auth/test_cases.py
manifest_template.yml
specification/example.yaml

AMB-1243 adding manifest file

---

.github/workflows/continuous-integration.yml

APM-4222 dont install node
